### ISSUE TITLE
Heroku deploy migration error

### ISSUE THREAD

**Issue by benichu** [montrealrb/Montreal.rb#165]
```
PG::NotNullViolation: ERROR:  column "location_id" contains null values
```

Source: https://travis-ci.org/montrealrb/Montreal.rb/builds/96755199#L641

**Comment by cawel** [comment]
I am surprised to see that there are locations already in prod db. Couldn't we just delete them and re-run the migrations again?

**Comment by benichu** [comment]
I think it was a old admin test... I'll take care of it tonight and redeploy...

**Comment by benichu** [comment]
My biggest problem is that I found out about the migration error by randomly drilling down travis-ci log...
Also related to this #140 - travis/heroku

**Comment by cawel** [comment]
Maybe TravisCI is configured to only notify Slack when "all is well", and do nothing if the deploy failed?

As for the issue at hand, removing all location rows from db should fix it.

**Comment by benichu** [comment]
removes the event with a nil location, ran migration, all is good.
I am still not very confident about the travis-ci + heroku deploy process, maybe my expectations are wrong:

1. merge code to master
2. build pass at Travis
3. code is deployed to heroku, migrations run if any
4. if any of the deploy tasks fail, keep the previous application release, and notify admins 

Not this:

![](http://storage.thouret.com.s3.amazonaws.com/monosnap/Slack_2015-12-14_19-08-15.jpg)

Anyway closing that issue for now...

**Comment by cawel** [comment]
Thanks for the screenshot. Indeed, it does not look like a failure.

And as you said, the deploy process is currently not optimal.
